[package]
name = "o2"
version = "0.1.0"
description = "Rust, without the iron-clad structure the borrow-checker provides"
edition = "2021"

[dependencies]
inkwell = { version = "0.5", features = ["llvm18-0"] }
